server:
  port: 8081

logging:
  level:
    root: debug

spring:
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      # consumer bootstrap servers? ?? ???? ??
      bootstrap-servers: 127.0.0.1:29092

      # ?? ??? Consumer Group Id
      group-id: test-group
      # Kafka ??? ?? offset? ???, ??? ?? offset? ? ?? ???? ?? ?? ??? ??? ??
      # latest: ?? ??? ??? ???? offeset reset
      # earliest: ?? ??? ???? offeset reset
      # none: offset ??? ??? Exception ??
      auto-offset-reset: earliest
      # ???? ??? ?, key/value? ????
      # JSON ???? ??? ???? JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # producer bootstrap servers? ?? ???? ??
      # bootstrap-servers: 3.34.97.97:9092

      # ???? ?? ?, key/value? ???
      # JSON ???? ?? ???? JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer